const freeze = Object.freeze;

/** Canonical frontend paths for every active backend API request. */
export const API_PATHS = freeze({
  auth: freeze({
    login: "/accounts/login/",
    refresh: "/accounts/refresh/",
    me: "/accounts/me/",
    users: "/accounts/users/",
    createUser: "/accounts/users/create/",
    user: (id) => `/accounts/users/${id}/`,
  }),
  public: freeze({
    home: "/public/home/",
    header: "/public/header/",
    footer: "/public/footer/",
    settings: "/public/settings/",
    dashboardStats: "/public/admin/dashboard-stats/",
  }),
  cms: freeze({
    publicHome: "/cms/public/home/",
    publicAbout: "/cms/public/about/",
    publicContact: "/cms/public/contact-page/",
    publicFaq: "/cms/public/faq/",
    publicSearch: "/cms/public/search/",
    publicContent: (slug) => `/cms/public/content/${slug}/`,
    adminAbout: "/cms/admin/about/",
    aboutStats: "/cms/admin/about/stats/",
    aboutStat: (id) => `/cms/admin/about/stats/${id}/`,
    aboutPosts: "/cms/admin/about/posts/",
    aboutPost: (id) => `/cms/admin/about/posts/${id}/`,
    aboutSections: "/cms/admin/about/sections/",
    aboutSection: (id) => `/cms/admin/about/sections/${id}/`,
    aboutIcons: "/cms/admin/about/icons/",
    aboutIcon: (id) => `/cms/admin/about/icons/${id}/`,
    aboutPartners: "/cms/admin/about/partners/",
    aboutPartner: (id) => `/cms/admin/about/partners/${id}/`,
    heroes: "/cms/admin/heroes/",
    hero: (id) => `/cms/admin/heroes/${id}/`,
    heroMedia: (heroId) => `/cms/admin/hero-media/${heroId}/`,
    heroMediaItem: (id) => `/cms/admin/hero-media/item/${id}/`,
    pages: "/cms/admin/pages/",
    page: (id) => `/cms/admin/pages/${id}/`,
    faqCategories: "/cms/admin/faq-categories/",
    faqCategory: (id) => `/cms/admin/faq-categories/${id}/`,
    faq: "/cms/admin/faq/",
    faqItem: (id) => `/cms/admin/faq/${id}/`,
    header: "/cms/admin/header/",
    headerItem: (id) => `/cms/admin/header/${id}/`,
    columns: "/cms/admin/columns/",
    column: (id) => `/cms/admin/columns/${id}/`,
    footerLinks: "/cms/admin/footer-links/",
    footerLink: (id) => `/cms/admin/footer-links/${id}/`,
    footerSettings: "/cms/admin/footer/settings/",
    footerCtas: "/cms/admin/footer/cta/",
    footerCta: (id) => `/cms/admin/footer/cta/${id}/`,
    contactPage: "/cms/admin/contact/page/",
    contactFaqPreview: "/cms/admin/contact/faq-preview/",
    contactFaqToggle: "/cms/admin/contact/faq-preview/toggle/",
    contactCards: "/cms/admin/contact/cards/",
    contactCard: (id) => `/cms/admin/contact/cards/${id}/`,
    pageContent: (slug) => `/cms/admin/page-content/${slug}/`,
  }),
  blog: freeze({
    publicSettings: "/blog/settings/",
    publicCategories: "/blog/categories/",
    publicPosts: "/blog/posts/",
    publicPost: (slug) => `/blog/posts/${slug}/`,
    categories: "/blog/admin/categories/",
    category: (id) => `/blog/admin/categories/${id}/`,
    tags: "/blog/admin/tags/",
    tag: (id) => `/blog/admin/tags/${id}/`,
    posts: "/blog/admin/posts/",
    post: (id) => `/blog/admin/posts/${id}/`,
    adminSettings: "/blog/admin/settings/",
  }),
  services: freeze({
    mainServices: "/services/admin/main-services/",
    mainService: (id) => `/services/admin/main-services/${id}/`,
    services: "/services/admin/services/",
    service: (id) => `/services/admin/services/${id}/`,
    sections: "/services/admin/service-sections/",
    section: (id) => `/services/admin/service-sections/${id}/`,
    page: "/services/admin/services-page/",
    pageItem: (id) => `/services/admin/services-page/${id}/`,
    requests: "/services/admin/service-advisory-requests/",
    request: (id) => `/services/admin/service-advisory-requests/${id}/`,
    import: "/services/admin/import-services/",
    publicMainServices: "/services/public/main-services/",
    publicServices: "/services/public/services/",
    publicPage: "/services/public/services-page/",
    publicCareers: "/services/public/careers/jobs/",
    requestLinks: (id) => `/services/admin/service-advisory-requests/${id}/access-links/`,
    createRequestLink: (id) => `/services/admin/service-advisory-requests/${id}/access-links/create/`,
    revokeLink: (id) => `/services/admin/request-access-links/${id}/revoke/`,
    regenerateLink: (id) => `/services/admin/request-access-links/${id}/regenerate/`,
    updateSubmission: (id) => `/services/admin/submissions/${id}/update/`,
    submissionHistory: (id) => `/services/admin/submissions/${id}/history/`,
    requestLogs: (id) => `/services/admin/service-advisory-requests/${id}/logs/`,
    sendOtp: "/services/public/request-access/send-otp/",
    verifyOtp: "/services/public/request-access/verify-otp/",
    editableRequest: (key) => `/services/public/request-access/${key}/`,
    updateEditableRequest: (key) => `/services/public/request-access/${key}/update/`,
  }),
  appointments: freeze({
    publicSlots: "/services/public/appointments/slots/",
    page: "/services/admin/appointments/page/",
    settings: "/services/admin/appointments/settings/",
    slots: "/services/admin/appointments/slots/",
    slot: (id) => `/services/admin/appointments/slots/${id}/`,
    bookings: "/services/admin/appointments/bookings/",
    generateSlots: "/services/admin/appointments/slots/generate/",
    bookingStatus: (id) => `/services/admin/appointments/bookings/${id}/status/`,
  }),
  careers: freeze({
    jobs: "/services/admin/careers/jobs/",
    job: (id) => `/services/admin/careers/jobs/${id}/`,
    applications: "/services/admin/careers/applications/",
  }),
  forms: freeze({
    admin: "/admin/forms/",
    adminForm: (id) => `/admin/forms/${id}/`,
    submissions: "/admin/form-submissions/",
    publicForm: (slug) => `/public/forms/${slug}/`,
    submit: (slug) => `/public/forms/${slug}/submit/`,
    successResponses: "/admin/success-responses/",
    successResponse: (id) => `/admin/success-responses/${id}/`,
    sections: (formId) => `/admin/forms/${formId}/sections/`,
    section: (id) => `/admin/forms/sections/${id}/`,
    fields: (formId) => `/admin/forms/${formId}/fields/`,
    field: (id) => `/admin/forms/fields/${id}/`,
    options: (fieldId) => `/admin/forms/fields/${fieldId}/options/`,
    option: (id) => `/admin/forms/options/${id}/`,
    infoModals: "/admin/info-modals/",
  }),
  legal: freeze({
    publicPage: (slug) => `/legal/page/${slug}/`,
    pages: "/legal/admin/pages/",
    page: (id) => `/legal/admin/pages/${id}/`,
  }),
  messaging: freeze({
    contact: "/messaging/contact/",
    subscribe: "/messaging/subscribe/",
    messages: "/messaging/admin/messages/",
    message: (id) => `/messaging/admin/messages/${id}/`,
    subscribers: "/messaging/admin/subscribers/",
    subscriber: (id) => `/messaging/admin/subscribers/${id}/`,
    subscriberExport: "/messaging/admin/subscribers/export/",
    broadcast: "/messaging/admin/broadcast/",
    broadcastLogs: "/messaging/admin/broadcast/logs/",
    emailTemplates: "/messaging/admin/email-templates/",
  }),
  settings: freeze({
    site: "/settings/",
    email: "/settings/email/",
  }),
  seo: freeze({
    adminDefault: "/seo/admin/default/",
    allPages: "/seo/admin/all-pages/",
    pages: "/seo/admin/pages/",
    page: (id) => `/seo/admin/pages/${id}/`,
  }),
});
